/**
 * @file Automatically generated by barrelsby.
 */

export * from "./capitalize";
export * from "./countWords";
export * from "./countWordsMatching";
export * from "./decodeURL";
export * from "./diffStrings";
export * from "./encodeURL";
export * from "./invertCase";
export * from "./isAnagram";
export * from "./isEmail";
export * from "./isPalindrome";
export * from "./isURL";
export * from "./maskEmail";
export * from "./removeSpaces";
export * from "./reverse";
export * from "./toCamelCase";
export * from "./toSlug";
export * from "./truncate";
